<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PizzaInventory\InventoryCatalogItem;

class InventoryCatalogSeeder extends Seeder
{
    public function run(): void
    {
        // Put your real names here.
        $items = [
           ['item_id' => '4760', 'name' => 'WING TRAY EMBOSSED LID - غطاء علبة الجوانح'],
            ['item_id' => '404', 'name' => 'GF LC SHRED BLEND CHEESE- الجبنة العادية'],
            ['item_id' => '3932', 'name' => 'TWIX COOKIE DOUGH BROWNIE - تويكس '],
            ['item_id' => '3', 'name' => '20 oz  beverage جميع المشروبات حجم 20 اونصة '],
            ['item_id' => '2', 'name' => '2L beverage جميع المشروبات حجم 2ليتر '],
            ['item_id' => '4658', 'name' => '5.75" CRAZY PUFF BOX - كراتين كريزي بافس'],
            ['item_id' => '5858', 'name' => '5.75" CRAZY PUFF BOX - كراتين كريزي بافس '],
            ['item_id' => '4759', 'name' => '16 OZ WING TRAY - علبة الجوانح'],
            ['item_id' => '4659', 'name' => '9X7 BOX GENERIC - كراتين اللانش كومبو الجديدة'],
            ['item_id' => '1103', 'name' => 'Chicken fully cooked - جوانح'],
            ['item_id' => '389', 'name' => 'STRING CHEESE - جبنة الأصابع'],
            ['item_id' => '4660', 'name' => 'WHITE 14 PIZZA BOX - كراتين البيتزا'],
            ['item_id' => '3929', 'name' => 'COOKIE BROWNIE  M&MS  - سمارتي'],
            ['item_id' => '11', 'name' => '16 OZ ENERGY DRINK جميع مشروبات الطاقة 16 اونصة '],
            ['item_id' => '17', 'name' => '16 OZ Mountain Dew Mango Rush - مشروب المانجو 16 اونص '],
            ['item_id' => '3150', 'name' => 'PEPPER RINGS MILD IN PET - قطرميزات حلقات فليفلة'],
            ['item_id' => '1515', 'name' => 'Flour - طحين'],
            ['item_id' => '4524', 'name' => 'PIZZA LINERS - كرتون تحت الديب ديش'],
            ['item_id' => '3144', 'name' => 'OLIVES SLC RIPE POUCH - الزيتون المقطع'],
            ['item_id' => '967', 'name' => 'SEASONED COOKED BEEF - لحمة الغنم المطبوخة '],
            ['item_id' => '4846', 'name' => 'QUILT WRAP 15 X 10.75 - ورق اللفة الاولى للكريزي بريد '],
            ['item_id' => '3203', 'name' => 'BUFFALO RANCH DIP CUP CLEAN LABEL - ديب كب بافلو رانش'],
            ['item_id' => '393', 'name' => 'جبنة الشيدر- Cheddar Cheese'],
            ['item_id' => '1040', 'name' => 'SPICY PEPPERONI -  بيبروني حارة'],
            ['item_id' => '1486', 'name' => 'Bakery deep dish- عجينة الديب الديش الجاهزة '],
            ['item_id' => '1612', 'name' => '14" THIN CRUST PIZZA PRESERVATIVE FREE - بيتزا رقيقة جاهزة'],
            ['item_id' => '456', 'name' => 'PRBLD FRESH GRTD PARM CHEESE W/ SALT - جبنة البازمزان الناعمة مع الملح (للستف كرست )'],
            ['item_id' => '4342', 'name' => 'CRAZY BREAD BAG - ورق تغليف الكريزي بريد البراني'],
            ['item_id' => '4841', 'name' => '12" PARCHMENT PAPER - ورق زبدة لصواني الجوانح'],
            ['item_id' => '4785', 'name' => '20x28 Dough tray sheet '],
            ['item_id' => '4923', 'name' => 'LCE DOUGH MIX WITH PADY POUCH - خميرة الديب ديش'],
            ['item_id' => '1723', 'name' => 'OIL VEGETABLE - الزيت النباتي'],
            ['item_id' => '3835', 'name' => 'BUFFALO HOT SAUCE - صلصة البافلو الحارة'],
            ['item_id' => '1042', 'name' => 'SLICED PEPPERONI - بيبروني'],
            ['item_id' => '5108', 'name' => 'PRETZEL SALT - ملح لصنف البرتزل'],
            ['item_id' => '3204', 'name' => 'CHEEZY JALAPENO DIP CUP CLEAN LABEL- كاب الهالبينو '],
            ['item_id' => '3860', 'name' => 'GARLIC PARMESAN WING SAUCE - صوص الجوانح بطعمة الجبن'],
            ['item_id' => '3201', 'name' => 'RANCH DIP CUP CLEAN LABEL - كب صوص الرانش'],
            ['item_id' => '3157', 'name' => 'JALAPENO PEPPERS - فليفلة الهاليبينو'],
            ['item_id' => '953', 'name' => 'CKD ITALIAN SAUSAGE CRUMBLES - سجق'],
            ['item_id' => '4230', 'name' => ' BAG CARRYOUT TOTE - كياس نايلون للزبائن'],
            ['item_id' => '4006', 'name' => 'LC DEEP DISH OIL BLEND CL -  زيت صواني الديب ديش'],
            ['item_id' => '920', 'name' => 'FRZ SMOKED JULIENNE HAM WA - هام'],
            ['item_id' => '4930', 'name' => 'VEGGIE SEASONING - زرف البهارات النباتي'],
            ['item_id' => '5031', 'name' => 'SEASONING- ITALIAN ZAP PACK زرف البهارات الصغير '],
            ['item_id' => '4969', 'name' => 'BAKING SODA - ملح ابيض'],
            ['item_id' => '1095', 'name' => 'APPLEWOOD SMOKED BACON  - لحم مقدد'],
            ['item_id' => '3638', 'name' => 'PINEAPPLE 20 OZ CAN TIDBITS - الاناناس المقطع'],
            ['item_id' => '4943', 'name' => 'LC LG SPICE BLEND - خلطة بهارات'],
            ['item_id' => '340', 'name' => 'SPREAD CRAZY BREAD - زبدة الكريزي بريد (السمنة)'],
            ['item_id' => '4922', 'name' => '4 OZ BAKERS YEAST - خميرة'],
            ['item_id' => '3858', 'name' => 'SMOKEY BBQ SAUCE  - صوص الباربيكيو المدخن'],
            ['item_id' => '4913', 'name' => 'DOUGH PRESS MIX - خميرة'],
            ['item_id' => '4336', 'name' => ' pan liner quilon baking sheet  ورق زبدة صواني الكريزي بريد _ '],
            ['item_id' => '3813', 'name' => 'LC PIZZA SAUCE - بيتزا صوص'],
            ['item_id' => '4781', 'name' => '5 OZ SAUCE CUP - LC - كاسة الصوص'],
            ['item_id' => '92506', 'name' => 'LC AGED CHEDDAR SAUCE POUCH - صوص جبنة الشيدر'],
            ['item_id' => '3705', 'name' => 'MUSHROOMS CUSTOM CUT CANNED - الفطر المقطع'],
            ['item_id' => '4782', 'name' => '5 OZ SAUCE CUP LID LC - غطاء كاسة الصوص'],
            ['item_id' => '4790', 'name' => '14X14 HDPE SMOOTH FILM SHEETS - غطا النايلون للصنية الصغيري '],
            ['item_id' => '476', 'name' => 'PARMESAN ASIAGO SHRED - جبنة بارميزان مبروشة'],
            ['item_id' => '349', 'name' => 'Margerina Liquid- سمنة البريتزل '],
            ['item_id' => '9218', 'name' => 'RELEASE OIL - زيت صواني البيتزا الدائرية (مكنة الزيت)'],
            ['item_id' => '6938', 'name' => 'NAPKIN MORNAP JR  -  محارم الزبائن'],
            ['item_id' => '3202', 'name' => 'BUTTERY GARLIC DIP CUP CL - كاب صوص الثوم '],
            ['item_id' => '5103', 'name' => 'PEPPER CRUSHED RED 1 GRAM ظرف البهارات فليفلة حمرا'],
            ['item_id' => '3636', 'name' => 'PINEAPPLE 10 CAN TIDBITS - الاناناس المقطع الصغير '],
            ['item_id' => '4786', 'name' => '17 X 12 HDPE EMBOSSED SHEETS- الغطا النايلون للصواني الكبار '],
            ['item_id' => '1065', 'name' => 'FV SLICED BEEF STEAK WITH ONIONS - لحم بقر مقطع مع البصل (العرض الجديد)'],
            ['item_id' => '92514', 'name' => 'Cheddar Garlic Sauce - صلصة تشيدر بالثوم (العرض الجديد)'],
            ['item_id' => '6209', 'name' => 'Bleach Cleaner - معقم كلور'],
            ['item_id' => '5647', 'name' => 'مواد تنظيف - Orange pro'],
            ['item_id' => '5648', 'name' => 'Glass cleaner - منظف الزجاج'],
            ['item_id' => '6200', 'name' => 'LMentary floor cleaner - منظف الارضيات الجديد'],
            ['item_id' => '5646', 'name' => 'Sanitizer - SUPER SAN SANITIZER'],
            ['item_id' => '5645', 'name' => 'Guardian - صابون جلي'],
            ['item_id' => '5474', 'name' => 'Sanitizer test - شرائط اختبار المعقم'],
            ['item_id' => '6210', 'name' => 'Liquid Cleaner - للمراحيض'],
            ['item_id' => '5748', 'name' => 'كياس زبالة قياس كبير 48/43 - BAGS TRASH 56 GAL '],
            ['item_id' => '6205', 'name' => 'Hand soap - الموديل الجديد'],
            ['item_id' => '5622', 'name' => 'كياس زبالة قياس صغير 39/33 - BAGS TRASH 33 GAL'],
            ['item_id' => '5532', 'name' => 'محارم تنشيف ايدين - TOWEL NATURAL'],
            ['item_id' => '5651', 'name' => 'Hand soap - الموديل القديم'],
            ['item_id' => '5632', 'name' => 'Excellent floor cleaner - منظفات ارضيات'],
            ['item_id' => '5650', 'name' => 'معقم ايدين الموديل القديم - hand sanitizer'],
            ['item_id' => '4540', 'name' => 'BOX DEEP DISH WHITE - كراتين الديب ديش'],
            ['item_id' => '3930', 'name' => 'Cookies '],
            ['item_id' => '5690', 'name' => 'Degreaser Cleaner- منظفات'],
            ['item_id' => '7422', 'name' => 'FRI 3/4 DISSOLVABLE LABEL (1M/ROLL) ستيكرات انتهاء الصلاحية'],
            ['item_id' => '7418', 'name' => 'MON 3/4" DISSOLVABLE LABEL (1M/ROLL)ستيكرات انتهاء الصلاحية'],
            ['item_id' => '7423', 'name' => 'SAT 3/4 DISSOLVABLE LABEL (1M/ROLL)ستيكرات انتهاء الصلاحية'],
            ['item_id' => '7424', 'name' => 'SUN 3/4 DISSOLVABLE LABEL (1M/ROLL)ستيكرات انتهاء الصلاحية'],
            ['item_id' => '7421', 'name' => 'THU 3/4 DISSOLVABLE LABEL (1M/ROLL)ستيكرات انتهاء الصلاحية'],
            ['item_id' => '7419', 'name' => 'TUE 3/4" DISSOLVABLE LABEL (1M/ROLL)ستيكرات انتهاء الصلاحية'],
            ['item_id' => '7420', 'name' => 'WED 3/4" DISSOLVABLE LABEL (1M/ROLL)ستيكرات انتهاء الصلاحية'],
            ['item_id' => '6934', 'name' => '9" COATED WHITE PLATE Pizza Paper (صحون ورق البيتزا)'],
            ['item_id' => '1710', 'name' => 'SLICED YELLOW ONIONS 1/4 IN - بصل'],
            ['item_id' => '1709', 'name' => 'SLICED PEPPER GREEN 1/4 IN - فليفلة خضراء مقطعة'],
            ['item_id' => '6304', 'name' => 'CV REGISTER TAPE - اوراق طابعة الكاشير  '],
            ['item_id' => '6319', 'name' => 'MAXSTICK 2GO DIAMOND - اوراق طابعة الستكرات للاندينغ  '],
            ['item_id' => 'محارمتواليتTISSUESTDBATH2PLY1000SHEET', 'name' => 'محارم تواليت - TISSUE STD BATH 2-PLY 1000 SHEET'],
        ];

        foreach ($items as $item) {
            InventoryCatalogItem::updateOrCreate(
                ['item_key' => $item['item_id']],
                ['item_name' => $item['name']]
            );
        }
    }
}
