<?php

namespace Database\Seeders;

use App\Models\PizzaInventory\Item;
use App\Models\PizzaInventory\Unit;
use Illuminate\Database\Seeder;

class PizzaInventorySeeder extends Seeder
{
    public function run(): void
    {
        // Seed Units
        $units = [
            ['name' => 'Case'],
            ['name' => 'Sleeves'],
            ['name' => 'Each'],
            ['name' => 'Bale'],
            ['name' => 'Bag'],
            ['name' => 'LB'],
            ['name' => 'Order'],
            ['name' => 'Pouch'],
            ['name' => 'Crate'],
            ['name' => 'Can'],
            ['name' => 'Jar'],
            ['name' => 'Pack'],
            ['name' => 'Bottle'],
            ['name' => 'PKG'],
            ['name' => 'Gallon'],
        ];

        foreach ($units as $unit) {
            Unit::create($unit);
        }

        // Seed Items
        $items = [
            ['item_id' => '4760', 'name' => ''],
            ['item_id' => '4526', 'name' => ''],
            ['item_id' => '404', 'name' => ''],
            ['item_id' => '3932', 'name' => ''],
            ['item_id' => '3', 'name' => ''],
            ['item_id' => '2', 'name' => ''],
            ['item_id' => '4658', 'name' => ''],
            ['item_id' => '5858', 'name' => ''],
            ['item_id' => '1', 'name' => ''],
            ['item_id' => '4759', 'name' => ''],
            ['item_id' => '4659', 'name' => ''],
            ['item_id' => '1103', 'name' => ''],
            ['item_id' => '389', 'name' => ''],
            ['item_id' => '4660', 'name' => ''],
            ['item_id' => '4606', 'name' => ''],
            ['item_id' => '3929', 'name' => ''],
            ['item_id' => '11', 'name' => ''],
            ['item_id' => '206', 'name' => ''],
            ['item_id' => '17', 'name' => ''],
            ['item_id' => '3150', 'name' => ''],
            ['item_id' => '1515', 'name' => ''],
            ['item_id' => '1799', 'name' => ''],
            ['item_id' => '1776', 'name' => ''],
            ['item_id' => '4524', 'name' => ''],
            ['item_id' => '3143', 'name' => ''],
            ['item_id' => '3141', 'name' => ''],
            ['item_id' => '3144', 'name' => ''],
            ['item_id' => '967', 'name' => ''],
            ['item_id' => '4846', 'name' => ''],
            ['item_id' => '3203', 'name' => ''],
            ['item_id' => '393', 'name' => ''],
            ['item_id' => '1040', 'name' => ''],
            ['item_id' => '1486', 'name' => ''],
            ['item_id' => '1612', 'name' => ''],
            ['item_id' => '456', 'name' => ''],
            ['item_id' => '4342', 'name' => ''],
            ['item_id' => '4334', 'name' => ''],
            ['item_id' => '4841', 'name' => ''],
            ['item_id' => '4785', 'name' => ''],
            ['item_id' => '4923', 'name' => ''],
            ['item_id' => '1723', 'name' => ''],
            ['item_id' => '3835', 'name' => ''],
            ['item_id' => '1042', 'name' => ''],
            ['item_id' => '5108', 'name' => ''],
            ['item_id' => '3204', 'name' => ''],
            ['item_id' => '3860', 'name' => ''],
            ['item_id' => '3201', 'name' => ''],
            ['item_id' => '3157', 'name' => ''],
            ['item_id' => '953', 'name' => ''],
            ['item_id' => '4230', 'name' => ''],
            ['item_id' => '4006', 'name' => ''],
            ['item_id' => '920', 'name' => ''],
            ['item_id' => '4930', 'name' => ''],
            ['item_id' => '5031', 'name' => ''],
            ['item_id' => '4969', 'name' => ''],
            ['item_id' => '1098', 'name' => ''],
            ['item_id' => '1095', 'name' => ''],
            ['item_id' => '3638', 'name' => ''],
            ['item_id' => '4943', 'name' => ''],
            ['item_id' => '340', 'name' => ''],
            ['item_id' => '4922', 'name' => ''],
            ['item_id' => '3858', 'name' => ''],
            ['item_id' => '4913', 'name' => ''],
            ['item_id' => '4336', 'name' => ''],
            ['item_id' => '1798', 'name' => ''],
            ['item_id' => '1790', 'name' => ''],
            ['item_id' => '3813', 'name' => ''],
            ['item_id' => '4781', 'name' => ''],
            ['item_id' => '92506', 'name' => ''],
            ['item_id' => '3705', 'name' => ''],
            ['item_id' => '4782', 'name' => ''],
            ['item_id' => '4790', 'name' => ''],
            ['item_id' => '476', 'name' => ''],
            ['item_id' => '349', 'name' => ''],
            ['item_id' => '9218', 'name' => ''],
            ['item_id' => '205', 'name' => ''],
            ['item_id' => '6938', 'name' => ''],
            ['item_id' => '3202', 'name' => ''],
            ['item_id' => '5103', 'name' => ''],
            ['item_id' => '468', 'name' => ''],
            ['item_id' => '3869', 'name' => ''],
            ['item_id' => '3636', 'name' => ''],
            ['item_id' => '4985', 'name' => ''],
            ['item_id' => '4786', 'name' => ''],
            ['item_id' => '4441', 'name' => ''],
            ['item_id' => '5107', 'name' => ''],
            ['item_id' => '4973', 'name' => ''],
            ['item_id' => '16', 'name' => ''],
            ['item_id' => '204', 'name' => ''],
            ['item_id' => '406', 'name' => ''],
            ['item_id' => '5106', 'name' => ''],
            ['item_id' => '5678', 'name' => ''],
            ['item_id' => 'DELIVERY', 'name' => ''],
            ['item_id' => '3000', 'name' => ''],
            ['item_id' => '5032', 'name' => ''],
            ['item_id' => '1041', 'name' => ''],
            ['item_id' => '1065', 'name' => ''],
            ['item_id' => '92514', 'name' => ''],
            ['item_id' => '427', 'name' => ''],
            ['item_id' => '6209', 'name' => ''],
            ['item_id' => '5647', 'name' => ''],
            ['item_id' => '5648', 'name' => ''],
            ['item_id' => '6200', 'name' => ''],
            ['item_id' => '5646', 'name' => ''],
            ['item_id' => '5645', 'name' => ''],
            ['item_id' => '5483', 'name' => ''],
            ['item_id' => '5474', 'name' => ''],
            ['item_id' => '6210A', 'name' => ''],
            ['item_id' => '5748', 'name' => ''],
            ['item_id' => '6208', 'name' => ''],
            ['item_id' => '6205', 'name' => ''],
            ['item_id' => '6201', 'name' => ''],
            ['item_id' => '5499', 'name' => ''],
            ['item_id' => '6203', 'name' => ''],
            ['item_id' => '5622', 'name' => ''],
            ['item_id' => '5505', 'name' => ''],
            ['item_id' => '5532', 'name' => ''],
            ['item_id' => '923', 'name' => ''],
            ['item_id' => '5651', 'name' => ''],
            ['item_id' => '5632', 'name' => ''],
            ['item_id' => '5909', 'name' => ''],
            ['item_id' => '5983', 'name' => ''],
            ['item_id' => '5496', 'name' => ''],
            ['item_id' => '5650', 'name' => ''],
            ['item_id' => '6202', 'name' => ''],
            ['item_id' => '4505', 'name' => ''],
            ['item_id' => '4515', 'name' => ''],
            ['item_id' => '3843', 'name' => ''],
            ['item_id' => '1766', 'name' => ''],
            ['item_id' => '4540', 'name' => ''],
            ['item_id' => '5652', 'name' => ''],
            ['item_id' => '8', 'name' => ''],
            ['item_id' => '1518', 'name' => ''],
            ['item_id' => '4961', 'name' => ''],
            ['item_id' => '4621', 'name' => ''],
            ['item_id' => '4795', 'name' => ''],
            ['item_id' => '4796', 'name' => ''],
            ['item_id' => '5653', 'name' => ''],
            ['item_id' => '202', 'name' => ''],
            ['item_id' => '339', 'name' => ''],
            ['item_id' => '3930', 'name' => ''],
            ['item_id' => '5690', 'name' => ''],
            ['item_id' => '5988', 'name' => ''],
            ['item_id' => '7422', 'name' => ''],
            ['item_id' => '7418', 'name' => ''],
            ['item_id' => '7423', 'name' => ''],
            ['item_id' => '7424', 'name' => ''],
            ['item_id' => '7421', 'name' => ''],
            ['item_id' => '7419', 'name' => ''],
            ['item_id' => '7420', 'name' => ''],
            ['item_id' => '6934', 'name' => ''],
            ['item_id' => '1710', 'name' => ''],
            ['item_id' => '1709', 'name' => ''],
            ['item_id' => '6304', 'name' => ''],
            ['item_id' => '6319', 'name' => ''],
        ];

        foreach ($items as $item) {
            Item::create($item);
        }
    }
}
