<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PizzaSchedule extends Model
{
    use HasFactory;
    protected $table = 'pizza_schedule';
    protected $fillable = [
        'store',
        'schedule_date',
        'hired_date',
        'hourly_base_pay',
        'hourly_performance_pay',
        'totally_pay',
        'position',
        'is_1099',
        'uniform',
        'num_of_shirts',
        'emp_id',
        'formula_emp_not_getting_hours_wanted',
        'at_only',
        'family',
        'car',
        'dob',
        'name',
        'red_in_schedule',
        'reads_in_schedule',
        'emp_id_alt',
        'new_team_member',
        'da_safety_score',
        'attendance',
        'score',
        'notes',
        'num_of_days',
        'reads_in_schedule_2',
        'cross_trained',
        'preference',
        'pt_ft',
        'name_alt',
        'rating',
        'maximum_hours',
        'hours_given',
        // Tuesday fields
        'tue_vci',
        'tue_in',
        'tue_out',
        'tue_status',
        'tue_total_hrs',
        'tue_op',
        'tue_m',
        'tue_l',
        'tue_c',
        'tue_status_f',
        'tue_hours_cost',
        'tue_hours',
        'tue_sales',
        'tue_4hrs',
        // Wednesday fields
        'wed_vc',
        'wed_in',
        'wed_out',
        'wed_status',
        'wed_total_hrs',
        'wed_op',
        'wed_m',
        'wed_l',
        'wed_c',
        'wed_status2',
        'wed_hours_cost',
        'wed_hours',
        'wed_sales',
        'wed_hrs',
        // Thursday fields
        'thu_vci',
        'thu_in',
        'thu_out',
        'thu_status',
        'thu_total_hrs',
        'thu_op',
        'thu_m',
        'thu_l',
        'thu_c',
        'thu_status_formula',
        'thu_hours_cost',
        'thu_hours',
        'thu_sales',
        'thu_4hrs',
        // Friday fields
        'fri_vci30',
        'fri_in',
        'fri_out',
        'fri_status',
        'fri_total_hrs',
        'fri_op',
        'fri_m',
        'fri_l',
        'fri_c',
        'fri_status_formula',
        'fri_hours_cost',
        'fri_hours',
        'fri_sales',
        'fri_4hrs',
        // Saturday fields
        'sat_vci44',
        'sat_in',
        'sat_out',
        'sat_status',
        'sat_total_hrs',
        'sat_op',
        'sat_m',
        'sat_l',
        'sat_c',
        'sat_status_formula',
        'sat_hours_cost',
        'sat_hours',
        'sat_sales',
        'sat_4hrs',
        // Sunday fields
        'sun_vci',
        'sun_in',
        'sun_out',
        'sun_status',
        'sun_total_hrs',
        'sun_op',
        'sun_m',
        'sun_l',
        'sun_c',
        'sun_status_formula',
        'sun_hours_cost',
        'sun_hours',
        'sun_sales',
        'sun_4hrs',
        // Sunday 2 fields
        'mon_vci',
        'mon_in',
        'mon_out',
        'mon_status',
        'mon_total_hrs',
        'mon_op',
        'mon_m',
        'mon_l',
        'mon_c',
        'mon_status_formula',
        'mon_hours_cost',
        'mon_hours',
        'mon_sales',
        'mon_4hrs',
        // Additional fields
        'x',
        'oje',
        'off_both_we',
        'status_not_filled',
        'hours_not_given',
        'dh_not_scheduled',
        'headcount',
        'weekend_not_filling_status',
        'weekly_hours',
        'ot_calc',
        'both_weekends',
        'px',
        't',
        're',
        'vci87',
        'excused_absence',
        'unexcused_absence',
        'late',
        'tenure_in_months',
        'hourly_base_pay_alt',
        'hourly_performance_pay_alt',
        'totally_pay_alt',
        'position_alt',
        'is_1099_alt',
        'total_pay',
    ];

    protected $casts = [
        'schedule_date' => 'date',
        'hired_date' => 'date',
        'dob' => 'date',
        'hourly_base_pay' => 'decimal:2',
        'hourly_performance_pay' => 'decimal:2',
        'totally_pay' => 'decimal:2',
        'maximum_hours' => 'decimal:2',
        'hours_given' => 'decimal:2',
        'tue_total_hrs' => 'decimal:2',
        'tue_hours_cost' => 'decimal:2',
        'tue_hours' => 'decimal:2',
        'tue_sales' => 'decimal:2',
        'wed_total_hrs' => 'decimal:2',
        'wed_hours_cost' => 'decimal:2',
        'wed_hours' => 'decimal:2',
        'wed_sales' => 'decimal:2',
        'thu_total_hrs' => 'decimal:2',
        'thu_hours_cost' => 'decimal:2',
        'thu_hours' => 'decimal:2',
        'thu_sales' => 'decimal:2',
        'fri_total_hrs' => 'decimal:2',
        'fri_hours_cost' => 'decimal:2',
        'fri_hours' => 'decimal:2',
        'fri_sales' => 'decimal:2',
        'sat_total_hrs' => 'decimal:2',
        'sat_hours_cost' => 'decimal:2',
        'sat_hours' => 'decimal:2',
        'sat_sales' => 'decimal:2',
        'sun_total_hrs' => 'decimal:2',
        'sun_hours_cost' => 'decimal:2',
        'sun_hours' => 'decimal:2',
        'sun_sales' => 'decimal:2',
        'sun_total_hrs2' => 'decimal:2',
        'sun_hours_cost2' => 'decimal:2',
        'sun_hours2' => 'decimal:2',
        'sun_sales2' => 'decimal:2',
        'weekly_hours' => 'decimal:2',
        'ot_calc' => 'decimal:2',
        'tenure_in_months' => 'decimal:2',
        'hourly_base_pay_alt' => 'decimal:2',
        'hourly_performance_pay_alt' => 'decimal:2',
        'totally_pay_alt' => 'decimal:2',
        'total_pay' => 'decimal:2',
    ];
}
